@startuml

/'! $CONFIG : toml
SmRunnerSettings.transpilerId = "CSharp"

[RenderConfig.CSharp]
NameSpace =  "BeziqueCore;"
'/

hide empty description
skinparam stateMessageAlignment center

[*] -> Deal


state Deal {
    state DealFirst
    state DealMid
    state DealLast

    [*] -> DealFirst
    DealFirst -> DealMid : Complete 
    DealMid -> DealLast : Complete
    DealLast -> SelectTrump : Complete 
    SelectTrump --> Play : Complete 
}

state Play {
    state PlayFirst
    state PlayMid
    state PlayLast
    
    [*] -> PlayFirst
    PlayFirst -> PlayMid : HasMid
    PlayMid -> PlayLast : Complete
    PlayFirst -> PlayLast : Complete
    PlayLast --> Meld
}

state Meld{
    [*] -> TryMelded
    state Melded
    state NoMeld
    
    TryMelded -> Melded : Success
    TryMelded -> NoMeld : Failed
    
    Melded -> AddPoint : Complete
    NoMeld --> NewTrick : Complete
    
}


AddPoint --> NewTrick : Complete

NewTrick -> AddOneCardToAll : Complete

AddOneCardToAll --> PlayFirst : Complete

AddOneCardToAll --> L9Play : DeckEmpty

state L9Play{
    state L9PlayFirst
    state L9PlayMid
    state L9PlayLast
    
    [*]-> L9PlayFirst
    L9PlayFirst --> L9PlayMid : Complete
    L9PlayMid --> L9PlayLast : Complete        
}

L9PlayLast --> L9NewTrick : Complete
L9NewTrick --> L9PlayFirst : CardsAvailable

L9NewTrick -> RoundEnd : NoCard
RoundEnd -> Deal : Continue


RoundEnd -> GameOver : WinningScore
NewTrick -> GameOver : WinningScore
L9NewTrick -> GameOver : WinningScore






@enduml