// Autogenerated with StateSmith 0.19.0-alpha-1+5931a3a68e50c80e83349118a90569bf08270686.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

#nullable enable

namespace BeziqueCore;

// Generated state machine
public partial class Bezique
{
    public enum EventId
    {
        DO = 0, // The `do` event is special. State event handlers do not consume this event (ancestors all get it too) unless a transition occurs.
        COMPLETE = 1,
        DECKEMPTY = 2,
        FAILED = 3,
        HASMID = 4,
        SUCCESS = 5,
    }

    public const int EventIdCount = 6;

    public enum StateId
    {
        ROOT = 0,
        ADDONECARDTOALL = 1,
        DEAL = 2,
        DEALFIRST = 3,
        DEALLAST = 4,
        DEALMID = 5,
        PLAY = 6,
        MELD = 7,
        ADDPOINT = 8,
        MELDED = 9,
        NEWTRICK = 10,
        NOMELD = 11,
        TRYMELDED = 12,
        PLAYFIRST = 13,
        PLAYLAST = 14,
        PLAYMID = 15,
        SELECTTRUMP = 16,
        L9PLAY = 17,
    }

    public const int StateIdCount = 18;

    // Used internally by state machine. Feel free to inspect, but don't modify.
    public StateId stateId;

    // State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
    public Bezique()
    {
    }

    // Starts the state machine. Must be called before dispatching events. Not thread safe.
    public void Start()
    {
        ROOT_enter();
        // ROOT behavior
        // uml: TransitionTo(ROOT.<InitialState>)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
            // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.

            // ROOT.<InitialState> behavior
            // uml: TransitionTo(Deal)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `Deal`.
                DEAL_enter();

                // Deal.<InitialState> behavior
                // uml: TransitionTo(DealFirst)
                {
                    // Step 1: Exit states until we reach `Deal` state (Least Common Ancestor for transition). Already at LCA, no exiting required.

                    // Step 2: Transition action: ``.

                    // Step 3: Enter/move towards transition target `DealFirst`.
                    DEALFIRST_enter();

                    // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                    return;
                } // end of behavior for Deal.<InitialState>
            } // end of behavior for ROOT.<InitialState>
        } // end of behavior for ROOT
    }

    // Dispatches an event to the state machine. Not thread safe.
    // Note! This function assumes that the `eventId` parameter is valid.
    public void DispatchEvent(EventId eventId)
    {
        switch (this.stateId)
        {
            // STATE: Bezique
            case StateId.ROOT:
                // No events handled by this state (or its ancestors).
                break;

            // STATE: AddOneCardToAll
            case StateId.ADDONECARDTOALL:
                switch (eventId)
                {
                    case EventId.COMPLETE: ADDONECARDTOALL_complete(); break;
                    case EventId.DECKEMPTY: ADDONECARDTOALL_deckempty(); break;
                }
                break;

            // STATE: Deal
            case StateId.DEAL:
                // No events handled by this state (or its ancestors).
                break;

            // STATE: DealFirst
            case StateId.DEALFIRST:
                switch (eventId)
                {
                    case EventId.COMPLETE: DEALFIRST_complete(); break;
                }
                break;

            // STATE: DealLast
            case StateId.DEALLAST:
                switch (eventId)
                {
                    case EventId.COMPLETE: DEALLAST_complete(); break;
                }
                break;

            // STATE: DealMid
            case StateId.DEALMID:
                switch (eventId)
                {
                    case EventId.COMPLETE: DEALMID_complete(); break;
                }
                break;

            // STATE: Play
            case StateId.PLAY:
                // No events handled by this state (or its ancestors).
                break;

            // STATE: Meld
            case StateId.MELD:
                // No events handled by this state (or its ancestors).
                break;

            // STATE: AddPoint
            case StateId.ADDPOINT:
                switch (eventId)
                {
                    case EventId.COMPLETE: ADDPOINT_complete(); break;
                }
                break;

            // STATE: Melded
            case StateId.MELDED:
                switch (eventId)
                {
                    case EventId.COMPLETE: MELDED_complete(); break;
                }
                break;

            // STATE: NewTrick
            case StateId.NEWTRICK:
                switch (eventId)
                {
                    case EventId.COMPLETE: NEWTRICK_complete(); break;
                }
                break;

            // STATE: NoMeld
            case StateId.NOMELD:
                switch (eventId)
                {
                    case EventId.COMPLETE: NOMELD_complete(); break;
                }
                break;

            // STATE: TryMelded
            case StateId.TRYMELDED:
                switch (eventId)
                {
                    case EventId.SUCCESS: TRYMELDED_success(); break;
                    case EventId.FAILED: TRYMELDED_failed(); break;
                }
                break;

            // STATE: PlayFirst
            case StateId.PLAYFIRST:
                switch (eventId)
                {
                    case EventId.HASMID: PLAYFIRST_hasmid(); break;
                    case EventId.COMPLETE: PLAYFIRST_complete(); break;
                }
                break;

            // STATE: PlayLast
            case StateId.PLAYLAST:
                switch (eventId)
                {
                    case EventId.DO: PLAYLAST_do(); break;
                }
                break;

            // STATE: PlayMid
            case StateId.PLAYMID:
                switch (eventId)
                {
                    case EventId.COMPLETE: PLAYMID_complete(); break;
                }
                break;

            // STATE: SelectTrump
            case StateId.SELECTTRUMP:
                switch (eventId)
                {
                    case EventId.COMPLETE: SELECTTRUMP_complete(); break;
                }
                break;

            // STATE: L9Play
            case StateId.L9PLAY:
                // No events handled by this state (or its ancestors).
                break;
        }

    }

    // This function is used when StateSmith doesn't know what the active leaf state is at
    // compile time due to sub states or when multiple states need to be exited.
    private void ExitUpToStateHandler(StateId desiredState)
    {
        while (this.stateId != desiredState)
        {
            switch (this.stateId)
            {
                case StateId.ADDONECARDTOALL: ADDONECARDTOALL_exit(); break;

                case StateId.DEAL: DEAL_exit(); break;

                case StateId.DEALFIRST: DEALFIRST_exit(); break;

                case StateId.DEALLAST: DEALLAST_exit(); break;

                case StateId.DEALMID: DEALMID_exit(); break;

                case StateId.PLAY: PLAY_exit(); break;

                case StateId.MELD: MELD_exit(); break;

                case StateId.ADDPOINT: ADDPOINT_exit(); break;

                case StateId.MELDED: MELDED_exit(); break;

                case StateId.NEWTRICK: NEWTRICK_exit(); break;

                case StateId.NOMELD: NOMELD_exit(); break;

                case StateId.TRYMELDED: TRYMELDED_exit(); break;

                case StateId.PLAYFIRST: PLAYFIRST_exit(); break;

                case StateId.PLAYLAST: PLAYLAST_exit(); break;

                case StateId.PLAYMID: PLAYMID_exit(); break;

                case StateId.SELECTTRUMP: SELECTTRUMP_exit(); break;

                case StateId.L9PLAY: L9PLAY_exit(); break;

                default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
            }
        }
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state ROOT
    ////////////////////////////////////////////////////////////////////////////////

    private void ROOT_enter()
    {
        this.stateId = StateId.ROOT;
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state ADDONECARDTOALL
    ////////////////////////////////////////////////////////////////////////////////

    private void ADDONECARDTOALL_enter()
    {
        this.stateId = StateId.ADDONECARDTOALL;
    }

    private void ADDONECARDTOALL_exit()
    {
        this.stateId = StateId.ROOT;
    }

    private void ADDONECARDTOALL_complete()
    {
        // AddOneCardToAll behavior
        // uml: Complete TransitionTo(PlayFirst)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            ADDONECARDTOALL_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `PlayFirst`.
            DEAL_enter();
            PLAY_enter();
            PLAYFIRST_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for AddOneCardToAll

        // No ancestor handles this event.
    }

    private void ADDONECARDTOALL_deckempty()
    {
        // AddOneCardToAll behavior
        // uml: DeckEmpty TransitionTo(L9Play)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            ADDONECARDTOALL_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `L9Play`.
            L9PLAY_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for AddOneCardToAll

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state DEAL
    ////////////////////////////////////////////////////////////////////////////////

    private void DEAL_enter()
    {
        this.stateId = StateId.DEAL;
    }

    private void DEAL_exit()
    {
        this.stateId = StateId.ROOT;
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state DEALFIRST
    ////////////////////////////////////////////////////////////////////////////////

    private void DEALFIRST_enter()
    {
        this.stateId = StateId.DEALFIRST;
    }

    private void DEALFIRST_exit()
    {
        this.stateId = StateId.DEAL;
    }

    private void DEALFIRST_complete()
    {
        // DealFirst behavior
        // uml: Complete TransitionTo(DealMid)
        {
            // Step 1: Exit states until we reach `Deal` state (Least Common Ancestor for transition).
            DEALFIRST_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `DealMid`.
            DEALMID_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for DealFirst

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state DEALLAST
    ////////////////////////////////////////////////////////////////////////////////

    private void DEALLAST_enter()
    {
        this.stateId = StateId.DEALLAST;
    }

    private void DEALLAST_exit()
    {
        this.stateId = StateId.DEAL;
    }

    private void DEALLAST_complete()
    {
        // DealLast behavior
        // uml: Complete TransitionTo(SelectTrump)
        {
            // Step 1: Exit states until we reach `Deal` state (Least Common Ancestor for transition).
            DEALLAST_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `SelectTrump`.
            SELECTTRUMP_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for DealLast

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state DEALMID
    ////////////////////////////////////////////////////////////////////////////////

    private void DEALMID_enter()
    {
        this.stateId = StateId.DEALMID;
    }

    private void DEALMID_exit()
    {
        this.stateId = StateId.DEAL;
    }

    private void DEALMID_complete()
    {
        // DealMid behavior
        // uml: Complete TransitionTo(DealLast)
        {
            // Step 1: Exit states until we reach `Deal` state (Least Common Ancestor for transition).
            DEALMID_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `DealLast`.
            DEALLAST_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for DealMid

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state PLAY
    ////////////////////////////////////////////////////////////////////////////////

    private void PLAY_enter()
    {
        this.stateId = StateId.PLAY;
    }

    private void PLAY_exit()
    {
        this.stateId = StateId.DEAL;
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state MELD
    ////////////////////////////////////////////////////////////////////////////////

    private void MELD_enter()
    {
        this.stateId = StateId.MELD;
    }

    private void MELD_exit()
    {
        this.stateId = StateId.PLAY;
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state ADDPOINT
    ////////////////////////////////////////////////////////////////////////////////

    private void ADDPOINT_enter()
    {
        this.stateId = StateId.ADDPOINT;
    }

    private void ADDPOINT_exit()
    {
        this.stateId = StateId.MELD;
    }

    private void ADDPOINT_complete()
    {
        // AddPoint behavior
        // uml: Complete TransitionTo(NewTrick)
        {
            // Step 1: Exit states until we reach `Meld` state (Least Common Ancestor for transition).
            ADDPOINT_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `NewTrick`.
            NEWTRICK_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for AddPoint

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state MELDED
    ////////////////////////////////////////////////////////////////////////////////

    private void MELDED_enter()
    {
        this.stateId = StateId.MELDED;
    }

    private void MELDED_exit()
    {
        this.stateId = StateId.MELD;
    }

    private void MELDED_complete()
    {
        // Melded behavior
        // uml: Complete TransitionTo(AddPoint)
        {
            // Step 1: Exit states until we reach `Meld` state (Least Common Ancestor for transition).
            MELDED_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `AddPoint`.
            ADDPOINT_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for Melded

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state NEWTRICK
    ////////////////////////////////////////////////////////////////////////////////

    private void NEWTRICK_enter()
    {
        this.stateId = StateId.NEWTRICK;
    }

    private void NEWTRICK_exit()
    {
        this.stateId = StateId.MELD;
    }

    private void NEWTRICK_complete()
    {
        // NewTrick behavior
        // uml: Complete TransitionTo(AddOneCardToAll)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            ExitUpToStateHandler(StateId.ROOT);

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `AddOneCardToAll`.
            ADDONECARDTOALL_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for NewTrick

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state NOMELD
    ////////////////////////////////////////////////////////////////////////////////

    private void NOMELD_enter()
    {
        this.stateId = StateId.NOMELD;
    }

    private void NOMELD_exit()
    {
        this.stateId = StateId.MELD;
    }

    private void NOMELD_complete()
    {
        // NoMeld behavior
        // uml: Complete TransitionTo(NewTrick)
        {
            // Step 1: Exit states until we reach `Meld` state (Least Common Ancestor for transition).
            NOMELD_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `NewTrick`.
            NEWTRICK_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for NoMeld

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state TRYMELDED
    ////////////////////////////////////////////////////////////////////////////////

    private void TRYMELDED_enter()
    {
        this.stateId = StateId.TRYMELDED;
    }

    private void TRYMELDED_exit()
    {
        this.stateId = StateId.MELD;
    }

    private void TRYMELDED_failed()
    {
        // TryMelded behavior
        // uml: Failed TransitionTo(NoMeld)
        {
            // Step 1: Exit states until we reach `Meld` state (Least Common Ancestor for transition).
            TRYMELDED_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `NoMeld`.
            NOMELD_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for TryMelded

        // No ancestor handles this event.
    }

    private void TRYMELDED_success()
    {
        // TryMelded behavior
        // uml: Success TransitionTo(Melded)
        {
            // Step 1: Exit states until we reach `Meld` state (Least Common Ancestor for transition).
            TRYMELDED_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `Melded`.
            MELDED_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for TryMelded

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state PLAYFIRST
    ////////////////////////////////////////////////////////////////////////////////

    private void PLAYFIRST_enter()
    {
        this.stateId = StateId.PLAYFIRST;
    }

    private void PLAYFIRST_exit()
    {
        this.stateId = StateId.PLAY;
    }

    private void PLAYFIRST_complete()
    {
        // PlayFirst behavior
        // uml: Complete TransitionTo(PlayLast)
        {
            // Step 1: Exit states until we reach `Play` state (Least Common Ancestor for transition).
            PLAYFIRST_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `PlayLast`.
            PLAYLAST_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for PlayFirst

        // No ancestor handles this event.
    }

    private void PLAYFIRST_hasmid()
    {
        // PlayFirst behavior
        // uml: HasMid TransitionTo(PlayMid)
        {
            // Step 1: Exit states until we reach `Play` state (Least Common Ancestor for transition).
            PLAYFIRST_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `PlayMid`.
            PLAYMID_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for PlayFirst

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state PLAYLAST
    ////////////////////////////////////////////////////////////////////////////////

    private void PLAYLAST_enter()
    {
        this.stateId = StateId.PLAYLAST;
    }

    private void PLAYLAST_exit()
    {
        this.stateId = StateId.PLAY;
    }

    private void PLAYLAST_do()
    {
        // PlayLast behavior
        // uml: do TransitionTo(Meld)
        {
            // Step 1: Exit states until we reach `Play` state (Least Common Ancestor for transition).
            PLAYLAST_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `Meld`.
            MELD_enter();

            // Meld.<InitialState> behavior
            // uml: TransitionTo(TryMelded)
            {
                // Step 1: Exit states until we reach `Meld` state (Least Common Ancestor for transition). Already at LCA, no exiting required.

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `TryMelded`.
                TRYMELDED_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for Meld.<InitialState>
        } // end of behavior for PlayLast

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state PLAYMID
    ////////////////////////////////////////////////////////////////////////////////

    private void PLAYMID_enter()
    {
        this.stateId = StateId.PLAYMID;
    }

    private void PLAYMID_exit()
    {
        this.stateId = StateId.PLAY;
    }

    private void PLAYMID_complete()
    {
        // PlayMid behavior
        // uml: Complete TransitionTo(PlayLast)
        {
            // Step 1: Exit states until we reach `Play` state (Least Common Ancestor for transition).
            PLAYMID_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `PlayLast`.
            PLAYLAST_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for PlayMid

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state SELECTTRUMP
    ////////////////////////////////////////////////////////////////////////////////

    private void SELECTTRUMP_enter()
    {
        this.stateId = StateId.SELECTTRUMP;
    }

    private void SELECTTRUMP_exit()
    {
        this.stateId = StateId.DEAL;
    }

    private void SELECTTRUMP_complete()
    {
        // SelectTrump behavior
        // uml: Complete TransitionTo(Play)
        {
            // Step 1: Exit states until we reach `Deal` state (Least Common Ancestor for transition).
            SELECTTRUMP_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `Play`.
            PLAY_enter();

            // Play.<InitialState> behavior
            // uml: TransitionTo(PlayFirst)
            {
                // Step 1: Exit states until we reach `Play` state (Least Common Ancestor for transition). Already at LCA, no exiting required.

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `PlayFirst`.
                PLAYFIRST_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for Play.<InitialState>
        } // end of behavior for SelectTrump

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state L9PLAY
    ////////////////////////////////////////////////////////////////////////////////

    private void L9PLAY_enter()
    {
        this.stateId = StateId.L9PLAY;
    }

    private void L9PLAY_exit()
    {
        this.stateId = StateId.ROOT;
    }

    // Thread safe.
    public static string StateIdToString(StateId id)
    {
        switch (id)
        {
            case StateId.ROOT: return "ROOT";
            case StateId.ADDONECARDTOALL: return "ADDONECARDTOALL";
            case StateId.DEAL: return "DEAL";
            case StateId.DEALFIRST: return "DEALFIRST";
            case StateId.DEALLAST: return "DEALLAST";
            case StateId.DEALMID: return "DEALMID";
            case StateId.PLAY: return "PLAY";
            case StateId.MELD: return "MELD";
            case StateId.ADDPOINT: return "ADDPOINT";
            case StateId.MELDED: return "MELDED";
            case StateId.NEWTRICK: return "NEWTRICK";
            case StateId.NOMELD: return "NOMELD";
            case StateId.TRYMELDED: return "TRYMELDED";
            case StateId.PLAYFIRST: return "PLAYFIRST";
            case StateId.PLAYLAST: return "PLAYLAST";
            case StateId.PLAYMID: return "PLAYMID";
            case StateId.SELECTTRUMP: return "SELECTTRUMP";
            case StateId.L9PLAY: return "L9PLAY";
            default: return "?";
        }
    }

    // Thread safe.
    public static string EventIdToString(EventId id)
    {
        switch (id)
        {
            case EventId.COMPLETE: return "COMPLETE";
            case EventId.DECKEMPTY: return "DECKEMPTY";
            case EventId.DO: return "DO";
            case EventId.FAILED: return "FAILED";
            case EventId.HASMID: return "HASMID";
            case EventId.SUCCESS: return "SUCCESS";
            default: return "?";
        }
    }
}
