// Autogenerated with StateSmith 0.19.0-alpha-1+5931a3a68e50c80e83349118a90569bf08270686.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

#nullable enable

// Generated state machine
public partial class BeziqueGameFlow
{
    public enum EventId
    {
        ALLHANDSEMPTY = 0,
        ALLPLAYERSRESPONDED = 1,
        CARDPLAYED = 2,
        CARDSDEALT = 3,
        CARDSDRAWN = 4,
        CONTINUEGAME = 5,
        CONTINUELASTNINE = 6,
        DECKEMPTY = 7,
        INITIALIZED = 8,
        MELDDECLARED = 9,
        MELDSCORED = 10,
        MELDSKIPPED = 11,
        MORECARDSAVAILABLE = 12,
        TIMEREXPIRED = 13,
        TIMERRESET = 14,
        TRICKRESOLVED = 15,
        TRUMPDETERMINED = 16,
        WINNINGSCOREREACHED = 17,
    }

    public const int EventIdCount = 18;

    public enum StateId
    {
        ROOT = 0,
        DEALING = 1,
        GAME_INIT = 2,
        GAME_OVER = 3,
        GAMEPLAY = 4,
        CARD_DRAW = 5,
        DECK_CHECK = 6,
        LAST_9_CARDS = 7,
        L9_OPPONENT_RESPONSE = 8,
        L9_PLAYER_TURN = 9,
        L9_TRICK_RESOLUTION = 10,
        MELD_OPPORTUNITY = 11,
        MELD_SCORING = 12,
        OPPONENT_RESPONSE = 13,
        PLAYER_TURN = 14,
        TRICK_RESOLUTION = 15,
        ROUND_END = 16,
        TIMER_TIMEOUT = 17,
        TRUMP_SELECTION = 18,
    }

    public const int StateIdCount = 19;

    // Used internally by state machine. Feel free to inspect, but don't modify.
    public StateId stateId;

    // State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
    public BeziqueGameFlow()
    {
    }

    // Starts the state machine. Must be called before dispatching events. Not thread safe.
    public void Start()
    {
        ROOT_enter();
        // ROOT behavior
        // uml: TransitionTo(ROOT.<InitialState>)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
            // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.

            // ROOT.<InitialState> behavior
            // uml: TransitionTo(GAME_INIT)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `GAME_INIT`.
                GAME_INIT_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for ROOT.<InitialState>
        } // end of behavior for ROOT
    }

    // Dispatches an event to the state machine. Not thread safe.
    // Note! This function assumes that the `eventId` parameter is valid.
    public void DispatchEvent(EventId eventId)
    {
        switch (this.stateId)
        {
            // STATE: BeziqueGameFlow
            case StateId.ROOT:
                // No events handled by this state (or its ancestors).
                break;

            // STATE: DEALING
            case StateId.DEALING:
                switch (eventId)
                {
                    case EventId.CARDSDEALT: DEALING_cardsdealt(); break;
                }
                break;

            // STATE: GAME_INIT
            case StateId.GAME_INIT:
                switch (eventId)
                {
                    case EventId.INITIALIZED: GAME_INIT_initialized(); break;
                }
                break;

            // STATE: GAME_OVER
            case StateId.GAME_OVER:
                // No events handled by this state (or its ancestors).
                break;

            // STATE: GAMEPLAY
            case StateId.GAMEPLAY:
                // No events handled by this state (or its ancestors).
                break;

            // STATE: CARD_DRAW
            case StateId.CARD_DRAW:
                switch (eventId)
                {
                    case EventId.CARDSDRAWN: CARD_DRAW_cardsdrawn(); break;
                }
                break;

            // STATE: DECK_CHECK
            case StateId.DECK_CHECK:
                switch (eventId)
                {
                    case EventId.DECKEMPTY: DECK_CHECK_deckempty(); break;
                    case EventId.MORECARDSAVAILABLE: DECK_CHECK_morecardsavailable(); break;
                }
                break;

            // STATE: LAST_9_CARDS
            case StateId.LAST_9_CARDS:
                switch (eventId)
                {
                    case EventId.ALLHANDSEMPTY: LAST_9_CARDS_allhandsempty(); break;
                }
                break;

            // STATE: L9_OPPONENT_RESPONSE
            case StateId.L9_OPPONENT_RESPONSE:
                switch (eventId)
                {
                    case EventId.ALLPLAYERSRESPONDED: L9_OPPONENT_RESPONSE_allplayersresponded(); break;
                    case EventId.ALLHANDSEMPTY: LAST_9_CARDS_allhandsempty(); break; // First ancestor handler for this event
                }
                break;

            // STATE: L9_PLAYER_TURN
            case StateId.L9_PLAYER_TURN:
                switch (eventId)
                {
                    case EventId.CARDPLAYED: L9_PLAYER_TURN_cardplayed(); break;
                    case EventId.TIMEREXPIRED: L9_PLAYER_TURN_timerexpired(); break;
                    case EventId.ALLHANDSEMPTY: LAST_9_CARDS_allhandsempty(); break; // First ancestor handler for this event
                }
                break;

            // STATE: L9_TRICK_RESOLUTION
            case StateId.L9_TRICK_RESOLUTION:
                switch (eventId)
                {
                    case EventId.CONTINUELASTNINE: L9_TRICK_RESOLUTION_continuelastnine(); break;
                    case EventId.ALLHANDSEMPTY: LAST_9_CARDS_allhandsempty(); break; // First ancestor handler for this event
                }
                break;

            // STATE: MELD_OPPORTUNITY
            case StateId.MELD_OPPORTUNITY:
                switch (eventId)
                {
                    case EventId.MELDDECLARED: MELD_OPPORTUNITY_melddeclared(); break;
                    case EventId.MELDSKIPPED: MELD_OPPORTUNITY_meldskipped(); break;
                }
                break;

            // STATE: MELD_SCORING
            case StateId.MELD_SCORING:
                switch (eventId)
                {
                    case EventId.MELDSCORED: MELD_SCORING_meldscored(); break;
                }
                break;

            // STATE: OPPONENT_RESPONSE
            case StateId.OPPONENT_RESPONSE:
                switch (eventId)
                {
                    case EventId.ALLPLAYERSRESPONDED: OPPONENT_RESPONSE_allplayersresponded(); break;
                }
                break;

            // STATE: PLAYER_TURN
            case StateId.PLAYER_TURN:
                switch (eventId)
                {
                    case EventId.CARDPLAYED: PLAYER_TURN_cardplayed(); break;
                    case EventId.TIMEREXPIRED: PLAYER_TURN_timerexpired(); break;
                }
                break;

            // STATE: TRICK_RESOLUTION
            case StateId.TRICK_RESOLUTION:
                switch (eventId)
                {
                    case EventId.TRICKRESOLVED: TRICK_RESOLUTION_trickresolved(); break;
                }
                break;

            // STATE: ROUND_END
            case StateId.ROUND_END:
                switch (eventId)
                {
                    case EventId.CONTINUEGAME: ROUND_END_continuegame(); break;
                    case EventId.WINNINGSCOREREACHED: ROUND_END_winningscorereached(); break;
                }
                break;

            // STATE: TIMER_TIMEOUT
            case StateId.TIMER_TIMEOUT:
                switch (eventId)
                {
                    case EventId.TIMERRESET: TIMER_TIMEOUT_timerreset(); break;
                }
                break;

            // STATE: TRUMP_SELECTION
            case StateId.TRUMP_SELECTION:
                switch (eventId)
                {
                    case EventId.TRUMPDETERMINED: TRUMP_SELECTION_trumpdetermined(); break;
                }
                break;
        }

    }

    // This function is used when StateSmith doesn't know what the active leaf state is at
    // compile time due to sub states or when multiple states need to be exited.
    private void ExitUpToStateHandler(StateId desiredState)
    {
        while (this.stateId != desiredState)
        {
            switch (this.stateId)
            {
                case StateId.DEALING: DEALING_exit(); break;

                case StateId.GAME_INIT: GAME_INIT_exit(); break;

                case StateId.GAME_OVER: GAME_OVER_exit(); break;

                case StateId.GAMEPLAY: GAMEPLAY_exit(); break;

                case StateId.CARD_DRAW: CARD_DRAW_exit(); break;

                case StateId.DECK_CHECK: DECK_CHECK_exit(); break;

                case StateId.LAST_9_CARDS: LAST_9_CARDS_exit(); break;

                case StateId.L9_OPPONENT_RESPONSE: L9_OPPONENT_RESPONSE_exit(); break;

                case StateId.L9_PLAYER_TURN: L9_PLAYER_TURN_exit(); break;

                case StateId.L9_TRICK_RESOLUTION: L9_TRICK_RESOLUTION_exit(); break;

                case StateId.MELD_OPPORTUNITY: MELD_OPPORTUNITY_exit(); break;

                case StateId.MELD_SCORING: MELD_SCORING_exit(); break;

                case StateId.OPPONENT_RESPONSE: OPPONENT_RESPONSE_exit(); break;

                case StateId.PLAYER_TURN: PLAYER_TURN_exit(); break;

                case StateId.TRICK_RESOLUTION: TRICK_RESOLUTION_exit(); break;

                case StateId.ROUND_END: ROUND_END_exit(); break;

                case StateId.TIMER_TIMEOUT: TIMER_TIMEOUT_exit(); break;

                case StateId.TRUMP_SELECTION: TRUMP_SELECTION_exit(); break;

                default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
            }
        }
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state ROOT
    ////////////////////////////////////////////////////////////////////////////////

    private void ROOT_enter()
    {
        this.stateId = StateId.ROOT;
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state DEALING
    ////////////////////////////////////////////////////////////////////////////////

    private void DEALING_enter()
    {
        this.stateId = StateId.DEALING;

        // DEALING behavior
        // uml: enter / { gameAdapter.DealCards(); }
        {
            // Step 1: execute action `gameAdapter.DealCards();`
            gameAdapter.DealCards();
        } // end of behavior for DEALING
    }

    private void DEALING_exit()
    {
        // DEALING behavior
        // uml: exit / { gameAdapter.NotifyCardsDealt(); }
        {
            // Step 1: execute action `gameAdapter.NotifyCardsDealt();`
            gameAdapter.NotifyCardsDealt();
        } // end of behavior for DEALING

        this.stateId = StateId.ROOT;
    }

    private void DEALING_cardsdealt()
    {
        // DEALING behavior
        // uml: CardsDealt TransitionTo(TRUMP_SELECTION)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            DEALING_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `TRUMP_SELECTION`.
            TRUMP_SELECTION_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for DEALING

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state GAME_INIT
    ////////////////////////////////////////////////////////////////////////////////

    private void GAME_INIT_enter()
    {
        this.stateId = StateId.GAME_INIT;

        // GAME_INIT behavior
        // uml: enter / { gameAdapter.InitializeGame(); }
        {
            // Step 1: execute action `gameAdapter.InitializeGame();`
            gameAdapter.InitializeGame();
        } // end of behavior for GAME_INIT
    }

    private void GAME_INIT_exit()
    {
        // GAME_INIT behavior
        // uml: exit / { gameAdapter.NotifyGameInitialized(); }
        {
            // Step 1: execute action `gameAdapter.NotifyGameInitialized();`
            gameAdapter.NotifyGameInitialized();
        } // end of behavior for GAME_INIT

        this.stateId = StateId.ROOT;
    }

    private void GAME_INIT_initialized()
    {
        // GAME_INIT behavior
        // uml: Initialized TransitionTo(DEALING)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            GAME_INIT_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `DEALING`.
            DEALING_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for GAME_INIT

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state GAME_OVER
    ////////////////////////////////////////////////////////////////////////////////

    private void GAME_OVER_enter()
    {
        this.stateId = StateId.GAME_OVER;

        // GAME_OVER behavior
        // uml: enter / { gameAdapter.DeclareWinner(); }
        {
            // Step 1: execute action `gameAdapter.DeclareWinner();`
            gameAdapter.DeclareWinner();
        } // end of behavior for GAME_OVER
    }

    private void GAME_OVER_exit()
    {
        // GAME_OVER behavior
        // uml: exit / { gameAdapter.NotifyGameOver(); }
        {
            // Step 1: execute action `gameAdapter.NotifyGameOver();`
            gameAdapter.NotifyGameOver();
        } // end of behavior for GAME_OVER

        this.stateId = StateId.ROOT;
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state GAMEPLAY
    ////////////////////////////////////////////////////////////////////////////////

    private void GAMEPLAY_enter()
    {
        this.stateId = StateId.GAMEPLAY;
    }

    private void GAMEPLAY_exit()
    {
        this.stateId = StateId.ROOT;
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state CARD_DRAW
    ////////////////////////////////////////////////////////////////////////////////

    private void CARD_DRAW_enter()
    {
        this.stateId = StateId.CARD_DRAW;

        // CARD_DRAW behavior
        // uml: enter / { gameAdapter.DrawCards(); }
        {
            // Step 1: execute action `gameAdapter.DrawCards();`
            gameAdapter.DrawCards();
        } // end of behavior for CARD_DRAW
    }

    private void CARD_DRAW_exit()
    {
        this.stateId = StateId.GAMEPLAY;
    }

    private void CARD_DRAW_cardsdrawn()
    {
        // CARD_DRAW behavior
        // uml: CardsDrawn TransitionTo(DECK_CHECK)
        {
            // Step 1: Exit states until we reach `GAMEPLAY` state (Least Common Ancestor for transition).
            CARD_DRAW_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `DECK_CHECK`.
            DECK_CHECK_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for CARD_DRAW

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state DECK_CHECK
    ////////////////////////////////////////////////////////////////////////////////

    private void DECK_CHECK_enter()
    {
        this.stateId = StateId.DECK_CHECK;

        // DECK_CHECK behavior
        // uml: enter / { gameAdapter.CheckDeck(); }
        {
            // Step 1: execute action `gameAdapter.CheckDeck();`
            gameAdapter.CheckDeck();
        } // end of behavior for DECK_CHECK
    }

    private void DECK_CHECK_exit()
    {
        this.stateId = StateId.GAMEPLAY;
    }

    private void DECK_CHECK_deckempty()
    {
        // DECK_CHECK behavior
        // uml: DeckEmpty TransitionTo(LAST_9_CARDS)
        {
            // Step 1: Exit states until we reach `GAMEPLAY` state (Least Common Ancestor for transition).
            DECK_CHECK_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `LAST_9_CARDS`.
            LAST_9_CARDS_enter();

            // LAST_9_CARDS.<InitialState> behavior
            // uml: TransitionTo(L9_PLAYER_TURN)
            {
                // Step 1: Exit states until we reach `LAST_9_CARDS` state (Least Common Ancestor for transition). Already at LCA, no exiting required.

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `L9_PLAYER_TURN`.
                L9_PLAYER_TURN_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for LAST_9_CARDS.<InitialState>
        } // end of behavior for DECK_CHECK

        // No ancestor handles this event.
    }

    private void DECK_CHECK_morecardsavailable()
    {
        // DECK_CHECK behavior
        // uml: MoreCardsAvailable TransitionTo(PLAYER_TURN)
        {
            // Step 1: Exit states until we reach `GAMEPLAY` state (Least Common Ancestor for transition).
            DECK_CHECK_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `PLAYER_TURN`.
            PLAYER_TURN_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for DECK_CHECK

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state LAST_9_CARDS
    ////////////////////////////////////////////////////////////////////////////////

    private void LAST_9_CARDS_enter()
    {
        this.stateId = StateId.LAST_9_CARDS;
    }

    private void LAST_9_CARDS_exit()
    {
        this.stateId = StateId.GAMEPLAY;
    }

    private void LAST_9_CARDS_allhandsempty()
    {
        // LAST_9_CARDS behavior
        // uml: AllHandsEmpty TransitionTo(ROUND_END)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            ExitUpToStateHandler(StateId.ROOT);

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `ROUND_END`.
            ROUND_END_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for LAST_9_CARDS

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state L9_OPPONENT_RESPONSE
    ////////////////////////////////////////////////////////////////////////////////

    private void L9_OPPONENT_RESPONSE_enter()
    {
        this.stateId = StateId.L9_OPPONENT_RESPONSE;

        // L9_OPPONENT_RESPONSE behavior
        // uml: enter / { gameAdapter.ProcessL9OpponentResponses(); }
        {
            // Step 1: execute action `gameAdapter.ProcessL9OpponentResponses();`
            gameAdapter.ProcessL9OpponentResponses();
        } // end of behavior for L9_OPPONENT_RESPONSE
    }

    private void L9_OPPONENT_RESPONSE_exit()
    {
        this.stateId = StateId.LAST_9_CARDS;
    }

    private void L9_OPPONENT_RESPONSE_allplayersresponded()
    {
        // L9_OPPONENT_RESPONSE behavior
        // uml: AllPlayersResponded TransitionTo(L9_TRICK_RESOLUTION)
        {
            // Step 1: Exit states until we reach `LAST_9_CARDS` state (Least Common Ancestor for transition).
            L9_OPPONENT_RESPONSE_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `L9_TRICK_RESOLUTION`.
            L9_TRICK_RESOLUTION_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for L9_OPPONENT_RESPONSE

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state L9_PLAYER_TURN
    ////////////////////////////////////////////////////////////////////////////////

    private void L9_PLAYER_TURN_enter()
    {
        this.stateId = StateId.L9_PLAYER_TURN;

        // L9_PLAYER_TURN behavior
        // uml: enter / { gameAdapter.StartPlayerTimer(); }
        {
            // Step 1: execute action `gameAdapter.StartPlayerTimer();`
            gameAdapter.StartPlayerTimer();
        } // end of behavior for L9_PLAYER_TURN
    }

    private void L9_PLAYER_TURN_exit()
    {
        // L9_PLAYER_TURN behavior
        // uml: exit / { gameAdapter.StopPlayerTimer(); }
        {
            // Step 1: execute action `gameAdapter.StopPlayerTimer();`
            gameAdapter.StopPlayerTimer();
        } // end of behavior for L9_PLAYER_TURN

        this.stateId = StateId.LAST_9_CARDS;
    }

    private void L9_PLAYER_TURN_cardplayed()
    {
        // L9_PLAYER_TURN behavior
        // uml: CardPlayed TransitionTo(L9_OPPONENT_RESPONSE)
        {
            // Step 1: Exit states until we reach `LAST_9_CARDS` state (Least Common Ancestor for transition).
            L9_PLAYER_TURN_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `L9_OPPONENT_RESPONSE`.
            L9_OPPONENT_RESPONSE_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for L9_PLAYER_TURN

        // No ancestor handles this event.
    }

    private void L9_PLAYER_TURN_timerexpired()
    {
        // L9_PLAYER_TURN behavior
        // uml: TimerExpired TransitionTo(TIMER_TIMEOUT)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            ExitUpToStateHandler(StateId.ROOT);

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `TIMER_TIMEOUT`.
            TIMER_TIMEOUT_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for L9_PLAYER_TURN

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state L9_TRICK_RESOLUTION
    ////////////////////////////////////////////////////////////////////////////////

    private void L9_TRICK_RESOLUTION_enter()
    {
        this.stateId = StateId.L9_TRICK_RESOLUTION;

        // L9_TRICK_RESOLUTION behavior
        // uml: enter / { gameAdapter.ResolveL9Trick(); }
        {
            // Step 1: execute action `gameAdapter.ResolveL9Trick();`
            gameAdapter.ResolveL9Trick();
        } // end of behavior for L9_TRICK_RESOLUTION
    }

    private void L9_TRICK_RESOLUTION_exit()
    {
        this.stateId = StateId.LAST_9_CARDS;
    }

    private void L9_TRICK_RESOLUTION_continuelastnine()
    {
        // L9_TRICK_RESOLUTION behavior
        // uml: ContinueLastNine TransitionTo(L9_PLAYER_TURN)
        {
            // Step 1: Exit states until we reach `LAST_9_CARDS` state (Least Common Ancestor for transition).
            L9_TRICK_RESOLUTION_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `L9_PLAYER_TURN`.
            L9_PLAYER_TURN_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for L9_TRICK_RESOLUTION

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state MELD_OPPORTUNITY
    ////////////////////////////////////////////////////////////////////////////////

    private void MELD_OPPORTUNITY_enter()
    {
        this.stateId = StateId.MELD_OPPORTUNITY;

        // MELD_OPPORTUNITY behavior
        // uml: enter / { gameAdapter.ProcessMeldOpportunity(); }
        {
            // Step 1: execute action `gameAdapter.ProcessMeldOpportunity();`
            gameAdapter.ProcessMeldOpportunity();
        } // end of behavior for MELD_OPPORTUNITY
    }

    private void MELD_OPPORTUNITY_exit()
    {
        this.stateId = StateId.GAMEPLAY;
    }

    private void MELD_OPPORTUNITY_melddeclared()
    {
        // MELD_OPPORTUNITY behavior
        // uml: MeldDeclared TransitionTo(MELD_SCORING)
        {
            // Step 1: Exit states until we reach `GAMEPLAY` state (Least Common Ancestor for transition).
            MELD_OPPORTUNITY_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `MELD_SCORING`.
            MELD_SCORING_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for MELD_OPPORTUNITY

        // No ancestor handles this event.
    }

    private void MELD_OPPORTUNITY_meldskipped()
    {
        // MELD_OPPORTUNITY behavior
        // uml: MeldSkipped TransitionTo(CARD_DRAW)
        {
            // Step 1: Exit states until we reach `GAMEPLAY` state (Least Common Ancestor for transition).
            MELD_OPPORTUNITY_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `CARD_DRAW`.
            CARD_DRAW_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for MELD_OPPORTUNITY

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state MELD_SCORING
    ////////////////////////////////////////////////////////////////////////////////

    private void MELD_SCORING_enter()
    {
        this.stateId = StateId.MELD_SCORING;

        // MELD_SCORING behavior
        // uml: enter / { gameAdapter.ScoreMeld(); }
        {
            // Step 1: execute action `gameAdapter.ScoreMeld();`
            gameAdapter.ScoreMeld();
        } // end of behavior for MELD_SCORING
    }

    private void MELD_SCORING_exit()
    {
        this.stateId = StateId.GAMEPLAY;
    }

    private void MELD_SCORING_meldscored()
    {
        // MELD_SCORING behavior
        // uml: MeldScored TransitionTo(CARD_DRAW)
        {
            // Step 1: Exit states until we reach `GAMEPLAY` state (Least Common Ancestor for transition).
            MELD_SCORING_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `CARD_DRAW`.
            CARD_DRAW_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for MELD_SCORING

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state OPPONENT_RESPONSE
    ////////////////////////////////////////////////////////////////////////////////

    private void OPPONENT_RESPONSE_enter()
    {
        this.stateId = StateId.OPPONENT_RESPONSE;

        // OPPONENT_RESPONSE behavior
        // uml: enter / { gameAdapter.ProcessOpponentResponses(); }
        {
            // Step 1: execute action `gameAdapter.ProcessOpponentResponses();`
            gameAdapter.ProcessOpponentResponses();
        } // end of behavior for OPPONENT_RESPONSE
    }

    private void OPPONENT_RESPONSE_exit()
    {
        this.stateId = StateId.GAMEPLAY;
    }

    private void OPPONENT_RESPONSE_allplayersresponded()
    {
        // OPPONENT_RESPONSE behavior
        // uml: AllPlayersResponded TransitionTo(TRICK_RESOLUTION)
        {
            // Step 1: Exit states until we reach `GAMEPLAY` state (Least Common Ancestor for transition).
            OPPONENT_RESPONSE_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `TRICK_RESOLUTION`.
            TRICK_RESOLUTION_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for OPPONENT_RESPONSE

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state PLAYER_TURN
    ////////////////////////////////////////////////////////////////////////////////

    private void PLAYER_TURN_enter()
    {
        this.stateId = StateId.PLAYER_TURN;

        // PLAYER_TURN behavior
        // uml: enter / { gameAdapter.StartPlayerTimer(); }
        {
            // Step 1: execute action `gameAdapter.StartPlayerTimer();`
            gameAdapter.StartPlayerTimer();
        } // end of behavior for PLAYER_TURN
    }

    private void PLAYER_TURN_exit()
    {
        // PLAYER_TURN behavior
        // uml: exit / { gameAdapter.StopPlayerTimer(); }
        {
            // Step 1: execute action `gameAdapter.StopPlayerTimer();`
            gameAdapter.StopPlayerTimer();
        } // end of behavior for PLAYER_TURN

        this.stateId = StateId.GAMEPLAY;
    }

    private void PLAYER_TURN_cardplayed()
    {
        // PLAYER_TURN behavior
        // uml: CardPlayed TransitionTo(OPPONENT_RESPONSE)
        {
            // Step 1: Exit states until we reach `GAMEPLAY` state (Least Common Ancestor for transition).
            PLAYER_TURN_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `OPPONENT_RESPONSE`.
            OPPONENT_RESPONSE_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for PLAYER_TURN

        // No ancestor handles this event.
    }

    private void PLAYER_TURN_timerexpired()
    {
        // PLAYER_TURN behavior
        // uml: TimerExpired TransitionTo(TIMER_TIMEOUT)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            ExitUpToStateHandler(StateId.ROOT);

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `TIMER_TIMEOUT`.
            TIMER_TIMEOUT_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for PLAYER_TURN

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state TRICK_RESOLUTION
    ////////////////////////////////////////////////////////////////////////////////

    private void TRICK_RESOLUTION_enter()
    {
        this.stateId = StateId.TRICK_RESOLUTION;

        // TRICK_RESOLUTION behavior
        // uml: enter / { gameAdapter.ResolveTrick(); }
        {
            // Step 1: execute action `gameAdapter.ResolveTrick();`
            gameAdapter.ResolveTrick();
        } // end of behavior for TRICK_RESOLUTION
    }

    private void TRICK_RESOLUTION_exit()
    {
        this.stateId = StateId.GAMEPLAY;
    }

    private void TRICK_RESOLUTION_trickresolved()
    {
        // TRICK_RESOLUTION behavior
        // uml: TrickResolved TransitionTo(MELD_OPPORTUNITY)
        {
            // Step 1: Exit states until we reach `GAMEPLAY` state (Least Common Ancestor for transition).
            TRICK_RESOLUTION_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `MELD_OPPORTUNITY`.
            MELD_OPPORTUNITY_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for TRICK_RESOLUTION

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state ROUND_END
    ////////////////////////////////////////////////////////////////////////////////

    private void ROUND_END_enter()
    {
        this.stateId = StateId.ROUND_END;

        // ROUND_END behavior
        // uml: enter / { gameAdapter.CalculateRoundScores(); }
        {
            // Step 1: execute action `gameAdapter.CalculateRoundScores();`
            gameAdapter.CalculateRoundScores();
        } // end of behavior for ROUND_END
    }

    private void ROUND_END_exit()
    {
        // ROUND_END behavior
        // uml: exit / { gameAdapter.NotifyRoundEnded(); }
        {
            // Step 1: execute action `gameAdapter.NotifyRoundEnded();`
            gameAdapter.NotifyRoundEnded();
        } // end of behavior for ROUND_END

        this.stateId = StateId.ROOT;
    }

    private void ROUND_END_continuegame()
    {
        // ROUND_END behavior
        // uml: ContinueGame TransitionTo(GAME_INIT)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            ROUND_END_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `GAME_INIT`.
            GAME_INIT_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ROUND_END

        // No ancestor handles this event.
    }

    private void ROUND_END_winningscorereached()
    {
        // ROUND_END behavior
        // uml: WinningScoreReached TransitionTo(GAME_OVER)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            ROUND_END_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `GAME_OVER`.
            GAME_OVER_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ROUND_END

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state TIMER_TIMEOUT
    ////////////////////////////////////////////////////////////////////////////////

    private void TIMER_TIMEOUT_enter()
    {
        this.stateId = StateId.TIMER_TIMEOUT;

        // TIMER_TIMEOUT behavior
        // uml: enter / { gameAdapter.DeductTimeoutPoints(); }
        {
            // Step 1: execute action `gameAdapter.DeductTimeoutPoints();`
            gameAdapter.DeductTimeoutPoints();
        } // end of behavior for TIMER_TIMEOUT
    }

    private void TIMER_TIMEOUT_exit()
    {
        // TIMER_TIMEOUT behavior
        // uml: exit / { gameAdapter.ResetPlayerTimer(); }
        {
            // Step 1: execute action `gameAdapter.ResetPlayerTimer();`
            gameAdapter.ResetPlayerTimer();
        } // end of behavior for TIMER_TIMEOUT

        this.stateId = StateId.ROOT;
    }

    private void TIMER_TIMEOUT_timerreset()
    {
        // TIMER_TIMEOUT behavior
        // uml: TimerReset TransitionTo(PLAYER_TURN)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            TIMER_TIMEOUT_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `PLAYER_TURN`.
            GAMEPLAY_enter();
            PLAYER_TURN_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for TIMER_TIMEOUT

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state TRUMP_SELECTION
    ////////////////////////////////////////////////////////////////////////////////

    private void TRUMP_SELECTION_enter()
    {
        this.stateId = StateId.TRUMP_SELECTION;

        // TRUMP_SELECTION behavior
        // uml: enter / { gameAdapter.FlipTrumpCard(); }
        {
            // Step 1: execute action `gameAdapter.FlipTrumpCard();`
            gameAdapter.FlipTrumpCard();
        } // end of behavior for TRUMP_SELECTION
    }

    private void TRUMP_SELECTION_exit()
    {
        // TRUMP_SELECTION behavior
        // uml: exit / { gameAdapter.NotifyTrumpDetermined(); }
        {
            // Step 1: execute action `gameAdapter.NotifyTrumpDetermined();`
            gameAdapter.NotifyTrumpDetermined();
        } // end of behavior for TRUMP_SELECTION

        this.stateId = StateId.ROOT;
    }

    private void TRUMP_SELECTION_trumpdetermined()
    {
        // TRUMP_SELECTION behavior
        // uml: TrumpDetermined TransitionTo(GAMEPLAY)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            TRUMP_SELECTION_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `GAMEPLAY`.
            GAMEPLAY_enter();

            // GAMEPLAY.<InitialState> behavior
            // uml: TransitionTo(PLAYER_TURN)
            {
                // Step 1: Exit states until we reach `GAMEPLAY` state (Least Common Ancestor for transition). Already at LCA, no exiting required.

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `PLAYER_TURN`.
                PLAYER_TURN_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for GAMEPLAY.<InitialState>
        } // end of behavior for TRUMP_SELECTION

        // No ancestor handles this event.
    }

    // Thread safe.
    public static string StateIdToString(StateId id)
    {
        switch (id)
        {
            case StateId.ROOT: return "ROOT";
            case StateId.DEALING: return "DEALING";
            case StateId.GAME_INIT: return "GAME_INIT";
            case StateId.GAME_OVER: return "GAME_OVER";
            case StateId.GAMEPLAY: return "GAMEPLAY";
            case StateId.CARD_DRAW: return "CARD_DRAW";
            case StateId.DECK_CHECK: return "DECK_CHECK";
            case StateId.LAST_9_CARDS: return "LAST_9_CARDS";
            case StateId.L9_OPPONENT_RESPONSE: return "L9_OPPONENT_RESPONSE";
            case StateId.L9_PLAYER_TURN: return "L9_PLAYER_TURN";
            case StateId.L9_TRICK_RESOLUTION: return "L9_TRICK_RESOLUTION";
            case StateId.MELD_OPPORTUNITY: return "MELD_OPPORTUNITY";
            case StateId.MELD_SCORING: return "MELD_SCORING";
            case StateId.OPPONENT_RESPONSE: return "OPPONENT_RESPONSE";
            case StateId.PLAYER_TURN: return "PLAYER_TURN";
            case StateId.TRICK_RESOLUTION: return "TRICK_RESOLUTION";
            case StateId.ROUND_END: return "ROUND_END";
            case StateId.TIMER_TIMEOUT: return "TIMER_TIMEOUT";
            case StateId.TRUMP_SELECTION: return "TRUMP_SELECTION";
            default: return "?";
        }
    }

    // Thread safe.
    public static string EventIdToString(EventId id)
    {
        switch (id)
        {
            case EventId.ALLHANDSEMPTY: return "ALLHANDSEMPTY";
            case EventId.ALLPLAYERSRESPONDED: return "ALLPLAYERSRESPONDED";
            case EventId.CARDPLAYED: return "CARDPLAYED";
            case EventId.CARDSDEALT: return "CARDSDEALT";
            case EventId.CARDSDRAWN: return "CARDSDRAWN";
            case EventId.CONTINUEGAME: return "CONTINUEGAME";
            case EventId.CONTINUELASTNINE: return "CONTINUELASTNINE";
            case EventId.DECKEMPTY: return "DECKEMPTY";
            case EventId.INITIALIZED: return "INITIALIZED";
            case EventId.MELDDECLARED: return "MELDDECLARED";
            case EventId.MELDSCORED: return "MELDSCORED";
            case EventId.MELDSKIPPED: return "MELDSKIPPED";
            case EventId.MORECARDSAVAILABLE: return "MORECARDSAVAILABLE";
            case EventId.TIMEREXPIRED: return "TIMEREXPIRED";
            case EventId.TIMERRESET: return "TIMERRESET";
            case EventId.TRICKRESOLVED: return "TRICKRESOLVED";
            case EventId.TRUMPDETERMINED: return "TRUMPDETERMINED";
            case EventId.WINNINGSCOREREACHED: return "WINNINGSCOREREACHED";
            default: return "?";
        }
    }
}
