// Autogenerated with StateSmith 0.19.0-alpha-1+5931a3a68e50c80e83349118a90569bf08270686.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

#nullable enable

namespace BeziqueCore;

// Generated state machine
public partial class Bezique
{
    public enum EventId
    {
        DO = 0, // The `do` event is special. State event handlers do not consume this event (ancestors all get it too) unless a transition occurs.
        COMPLETE = 1,
        DEALNOTCOMPLETE = 2,
        FOURPLAYERGAME = 3,
        OTHERCARD = 4,
        TRUMP7 = 5,
        TWOPLAYERGAME = 6,
    }

    public const int EventIdCount = 7;

    public enum StateId
    {
        ROOT = 0,
        ADD10POINTSTODEALER = 1,
        DEALFOURPLAYER = 2,
        DEAL4_FIRSTPLAYER = 3,
        DEAL4_FOURTHPLAYER = 4,
        DEAL4_SECONDPLAYER = 5,
        DEAL4_THIRDPLAYER = 6,
        DEALTWOPLAYER = 7,
        DEAL2_FIRSTPLAYER = 8,
        DEAL2_SECONDPLAYER = 9,
        FLIPTRUMP = 10,
        PLAYPHASE1 = 11,
        STARTGAME = 12,
    }

    public const int StateIdCount = 13;

    // Used internally by state machine. Feel free to inspect, but don't modify.
    public StateId stateId;

    // State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
    public Bezique()
    {
    }

    // Starts the state machine. Must be called before dispatching events. Not thread safe.
    public void Start()
    {
        ROOT_enter();
        // ROOT behavior
        // uml: TransitionTo(ROOT.<InitialState>)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
            // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.

            // ROOT.<InitialState> behavior
            // uml: TransitionTo(StartGame)
            {
                // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `StartGame`.
                STARTGAME_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for ROOT.<InitialState>
        } // end of behavior for ROOT
    }

    // Dispatches an event to the state machine. Not thread safe.
    // Note! This function assumes that the `eventId` parameter is valid.
    public void DispatchEvent(EventId eventId)
    {
        switch (this.stateId)
        {
            // STATE: Bezique
            case StateId.ROOT:
                // No events handled by this state (or its ancestors).
                break;

            // STATE: Add10PointsToDealer
            case StateId.ADD10POINTSTODEALER:
                switch (eventId)
                {
                    case EventId.DO: ADD10POINTSTODEALER_do(); break;
                }
                break;

            // STATE: DealFourPlayer
            case StateId.DEALFOURPLAYER:
                // No events handled by this state (or its ancestors).
                break;

            // STATE: Deal4_FirstPlayer
            case StateId.DEAL4_FIRSTPLAYER:
                switch (eventId)
                {
                    case EventId.COMPLETE: DEAL4_FIRSTPLAYER_complete(); break;
                }
                break;

            // STATE: Deal4_FourthPlayer
            case StateId.DEAL4_FOURTHPLAYER:
                switch (eventId)
                {
                    case EventId.DEALNOTCOMPLETE: DEAL4_FOURTHPLAYER_dealnotcomplete(); break;
                    case EventId.DO: DEAL4_FOURTHPLAYER_do(); break;
                }
                break;

            // STATE: Deal4_SecondPlayer
            case StateId.DEAL4_SECONDPLAYER:
                switch (eventId)
                {
                    case EventId.COMPLETE: DEAL4_SECONDPLAYER_complete(); break;
                }
                break;

            // STATE: Deal4_ThirdPlayer
            case StateId.DEAL4_THIRDPLAYER:
                switch (eventId)
                {
                    case EventId.COMPLETE: DEAL4_THIRDPLAYER_complete(); break;
                }
                break;

            // STATE: DealTwoPlayer
            case StateId.DEALTWOPLAYER:
                // No events handled by this state (or its ancestors).
                break;

            // STATE: Deal2_FirstPlayer
            case StateId.DEAL2_FIRSTPLAYER:
                switch (eventId)
                {
                    case EventId.COMPLETE: DEAL2_FIRSTPLAYER_complete(); break;
                }
                break;

            // STATE: Deal2_SecondPlayer
            case StateId.DEAL2_SECONDPLAYER:
                switch (eventId)
                {
                    case EventId.DEALNOTCOMPLETE: DEAL2_SECONDPLAYER_dealnotcomplete(); break;
                    case EventId.DO: DEAL2_SECONDPLAYER_do(); break;
                }
                break;

            // STATE: FlipTrump
            case StateId.FLIPTRUMP:
                switch (eventId)
                {
                    case EventId.TRUMP7: FLIPTRUMP_trump7(); break;
                    case EventId.OTHERCARD: FLIPTRUMP_othercard(); break;
                }
                break;

            // STATE: PlayPhase1
            case StateId.PLAYPHASE1:
                // No events handled by this state (or its ancestors).
                break;

            // STATE: StartGame
            case StateId.STARTGAME:
                switch (eventId)
                {
                    case EventId.TWOPLAYERGAME: STARTGAME_twoplayergame(); break;
                    case EventId.FOURPLAYERGAME: STARTGAME_fourplayergame(); break;
                }
                break;
        }

    }

    // This function is used when StateSmith doesn't know what the active leaf state is at
    // compile time due to sub states or when multiple states need to be exited.
    private void ExitUpToStateHandler(StateId desiredState)
    {
        while (this.stateId != desiredState)
        {
            switch (this.stateId)
            {
                case StateId.ADD10POINTSTODEALER: ADD10POINTSTODEALER_exit(); break;

                case StateId.DEALFOURPLAYER: DEALFOURPLAYER_exit(); break;

                case StateId.DEAL4_FIRSTPLAYER: DEAL4_FIRSTPLAYER_exit(); break;

                case StateId.DEAL4_FOURTHPLAYER: DEAL4_FOURTHPLAYER_exit(); break;

                case StateId.DEAL4_SECONDPLAYER: DEAL4_SECONDPLAYER_exit(); break;

                case StateId.DEAL4_THIRDPLAYER: DEAL4_THIRDPLAYER_exit(); break;

                case StateId.DEALTWOPLAYER: DEALTWOPLAYER_exit(); break;

                case StateId.DEAL2_FIRSTPLAYER: DEAL2_FIRSTPLAYER_exit(); break;

                case StateId.DEAL2_SECONDPLAYER: DEAL2_SECONDPLAYER_exit(); break;

                case StateId.FLIPTRUMP: FLIPTRUMP_exit(); break;

                case StateId.PLAYPHASE1: PLAYPHASE1_exit(); break;

                case StateId.STARTGAME: STARTGAME_exit(); break;

                default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
            }
        }
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state ROOT
    ////////////////////////////////////////////////////////////////////////////////

    private void ROOT_enter()
    {
        this.stateId = StateId.ROOT;
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state ADD10POINTSTODEALER
    ////////////////////////////////////////////////////////////////////////////////

    private void ADD10POINTSTODEALER_enter()
    {
        this.stateId = StateId.ADD10POINTSTODEALER;

        // Add10PointsToDealer behavior
        // uml: enter / { _adapter.Add10PointsToDealer(); }
        {
            // Step 1: execute action `_adapter.Add10PointsToDealer();`
            _adapter.Add10PointsToDealer();
        } // end of behavior for Add10PointsToDealer
    }

    private void ADD10POINTSTODEALER_exit()
    {
        this.stateId = StateId.ROOT;
    }

    private void ADD10POINTSTODEALER_do()
    {
        // Add10PointsToDealer behavior
        // uml: do TransitionTo(PlayPhase1)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            ADD10POINTSTODEALER_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `PlayPhase1`.
            PLAYPHASE1_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for Add10PointsToDealer

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state DEALFOURPLAYER
    ////////////////////////////////////////////////////////////////////////////////

    private void DEALFOURPLAYER_enter()
    {
        this.stateId = StateId.DEALFOURPLAYER;
    }

    private void DEALFOURPLAYER_exit()
    {
        this.stateId = StateId.ROOT;
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state DEAL4_FIRSTPLAYER
    ////////////////////////////////////////////////////////////////////////////////

    private void DEAL4_FIRSTPLAYER_enter()
    {
        this.stateId = StateId.DEAL4_FIRSTPLAYER;

        // Deal4_FirstPlayer behavior
        // uml: enter / { _adapter.DealThreeCards(); }
        {
            // Step 1: execute action `_adapter.DealThreeCards();`
            _adapter.DealThreeCards();
        } // end of behavior for Deal4_FirstPlayer
    }

    private void DEAL4_FIRSTPLAYER_exit()
    {
        this.stateId = StateId.DEALFOURPLAYER;
    }

    private void DEAL4_FIRSTPLAYER_complete()
    {
        // Deal4_FirstPlayer behavior
        // uml: Complete TransitionTo(Deal4_SecondPlayer)
        {
            // Step 1: Exit states until we reach `DealFourPlayer` state (Least Common Ancestor for transition).
            DEAL4_FIRSTPLAYER_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `Deal4_SecondPlayer`.
            DEAL4_SECONDPLAYER_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for Deal4_FirstPlayer

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state DEAL4_FOURTHPLAYER
    ////////////////////////////////////////////////////////////////////////////////

    private void DEAL4_FOURTHPLAYER_enter()
    {
        this.stateId = StateId.DEAL4_FOURTHPLAYER;

        // Deal4_FourthPlayer behavior
        // uml: enter / { _adapter.DealThreeCards(); }
        {
            // Step 1: execute action `_adapter.DealThreeCards();`
            _adapter.DealThreeCards();
        } // end of behavior for Deal4_FourthPlayer
    }

    private void DEAL4_FOURTHPLAYER_exit()
    {
        this.stateId = StateId.DEALFOURPLAYER;
    }

    private void DEAL4_FOURTHPLAYER_dealnotcomplete()
    {
        // Deal4_FourthPlayer behavior
        // uml: DealNotComplete TransitionTo(Deal4_FirstPlayer)
        {
            // Step 1: Exit states until we reach `DealFourPlayer` state (Least Common Ancestor for transition).
            DEAL4_FOURTHPLAYER_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `Deal4_FirstPlayer`.
            DEAL4_FIRSTPLAYER_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for Deal4_FourthPlayer

        // No ancestor handles this event.
    }

    private void DEAL4_FOURTHPLAYER_do()
    {
        // Deal4_FourthPlayer behavior
        // uml: do TransitionTo(FlipTrump)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            ExitUpToStateHandler(StateId.ROOT);

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `FlipTrump`.
            DEALTWOPLAYER_enter();
            FLIPTRUMP_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for Deal4_FourthPlayer

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state DEAL4_SECONDPLAYER
    ////////////////////////////////////////////////////////////////////////////////

    private void DEAL4_SECONDPLAYER_enter()
    {
        this.stateId = StateId.DEAL4_SECONDPLAYER;

        // Deal4_SecondPlayer behavior
        // uml: enter / { _adapter.DealThreeCards(); }
        {
            // Step 1: execute action `_adapter.DealThreeCards();`
            _adapter.DealThreeCards();
        } // end of behavior for Deal4_SecondPlayer
    }

    private void DEAL4_SECONDPLAYER_exit()
    {
        this.stateId = StateId.DEALFOURPLAYER;
    }

    private void DEAL4_SECONDPLAYER_complete()
    {
        // Deal4_SecondPlayer behavior
        // uml: Complete TransitionTo(Deal4_ThirdPlayer)
        {
            // Step 1: Exit states until we reach `DealFourPlayer` state (Least Common Ancestor for transition).
            DEAL4_SECONDPLAYER_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `Deal4_ThirdPlayer`.
            DEAL4_THIRDPLAYER_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for Deal4_SecondPlayer

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state DEAL4_THIRDPLAYER
    ////////////////////////////////////////////////////////////////////////////////

    private void DEAL4_THIRDPLAYER_enter()
    {
        this.stateId = StateId.DEAL4_THIRDPLAYER;

        // Deal4_ThirdPlayer behavior
        // uml: enter / { _adapter.DealThreeCards(); }
        {
            // Step 1: execute action `_adapter.DealThreeCards();`
            _adapter.DealThreeCards();
        } // end of behavior for Deal4_ThirdPlayer
    }

    private void DEAL4_THIRDPLAYER_exit()
    {
        this.stateId = StateId.DEALFOURPLAYER;
    }

    private void DEAL4_THIRDPLAYER_complete()
    {
        // Deal4_ThirdPlayer behavior
        // uml: Complete TransitionTo(Deal4_FourthPlayer)
        {
            // Step 1: Exit states until we reach `DealFourPlayer` state (Least Common Ancestor for transition).
            DEAL4_THIRDPLAYER_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `Deal4_FourthPlayer`.
            DEAL4_FOURTHPLAYER_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for Deal4_ThirdPlayer

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state DEALTWOPLAYER
    ////////////////////////////////////////////////////////////////////////////////

    private void DEALTWOPLAYER_enter()
    {
        this.stateId = StateId.DEALTWOPLAYER;
    }

    private void DEALTWOPLAYER_exit()
    {
        this.stateId = StateId.ROOT;
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state DEAL2_FIRSTPLAYER
    ////////////////////////////////////////////////////////////////////////////////

    private void DEAL2_FIRSTPLAYER_enter()
    {
        this.stateId = StateId.DEAL2_FIRSTPLAYER;

        // Deal2_FirstPlayer behavior
        // uml: enter / { _adapter.DealThreeCards(); }
        {
            // Step 1: execute action `_adapter.DealThreeCards();`
            _adapter.DealThreeCards();
        } // end of behavior for Deal2_FirstPlayer
    }

    private void DEAL2_FIRSTPLAYER_exit()
    {
        this.stateId = StateId.DEALTWOPLAYER;
    }

    private void DEAL2_FIRSTPLAYER_complete()
    {
        // Deal2_FirstPlayer behavior
        // uml: Complete TransitionTo(Deal2_SecondPlayer)
        {
            // Step 1: Exit states until we reach `DealTwoPlayer` state (Least Common Ancestor for transition).
            DEAL2_FIRSTPLAYER_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `Deal2_SecondPlayer`.
            DEAL2_SECONDPLAYER_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for Deal2_FirstPlayer

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state DEAL2_SECONDPLAYER
    ////////////////////////////////////////////////////////////////////////////////

    private void DEAL2_SECONDPLAYER_enter()
    {
        this.stateId = StateId.DEAL2_SECONDPLAYER;

        // Deal2_SecondPlayer behavior
        // uml: enter / { _adapter.DealThreeCards(); }
        {
            // Step 1: execute action `_adapter.DealThreeCards();`
            _adapter.DealThreeCards();
        } // end of behavior for Deal2_SecondPlayer
    }

    private void DEAL2_SECONDPLAYER_exit()
    {
        this.stateId = StateId.DEALTWOPLAYER;
    }

    private void DEAL2_SECONDPLAYER_dealnotcomplete()
    {
        // Deal2_SecondPlayer behavior
        // uml: DealNotComplete TransitionTo(Deal2_FirstPlayer)
        {
            // Step 1: Exit states until we reach `DealTwoPlayer` state (Least Common Ancestor for transition).
            DEAL2_SECONDPLAYER_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `Deal2_FirstPlayer`.
            DEAL2_FIRSTPLAYER_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for Deal2_SecondPlayer

        // No ancestor handles this event.
    }

    private void DEAL2_SECONDPLAYER_do()
    {
        // Deal2_SecondPlayer behavior
        // uml: do TransitionTo(FlipTrump)
        {
            // Step 1: Exit states until we reach `DealTwoPlayer` state (Least Common Ancestor for transition).
            DEAL2_SECONDPLAYER_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `FlipTrump`.
            FLIPTRUMP_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for Deal2_SecondPlayer

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state FLIPTRUMP
    ////////////////////////////////////////////////////////////////////////////////

    private void FLIPTRUMP_enter()
    {
        this.stateId = StateId.FLIPTRUMP;

        // FlipTrump behavior
        // uml: enter / { _adapter.FlipCard(); }
        {
            // Step 1: execute action `_adapter.FlipCard();`
            _adapter.FlipCard();
        } // end of behavior for FlipTrump
    }

    private void FLIPTRUMP_exit()
    {
        this.stateId = StateId.DEALTWOPLAYER;
    }

    private void FLIPTRUMP_othercard()
    {
        // FlipTrump behavior
        // uml: OtherCard TransitionTo(PlayPhase1)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            ExitUpToStateHandler(StateId.ROOT);

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `PlayPhase1`.
            PLAYPHASE1_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for FlipTrump

        // No ancestor handles this event.
    }

    private void FLIPTRUMP_trump7()
    {
        // FlipTrump behavior
        // uml: Trump7 TransitionTo(Add10PointsToDealer)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            ExitUpToStateHandler(StateId.ROOT);

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `Add10PointsToDealer`.
            ADD10POINTSTODEALER_enter();

            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for FlipTrump

        // No ancestor handles this event.
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state PLAYPHASE1
    ////////////////////////////////////////////////////////////////////////////////

    private void PLAYPHASE1_enter()
    {
        this.stateId = StateId.PLAYPHASE1;
    }

    private void PLAYPHASE1_exit()
    {
        this.stateId = StateId.ROOT;
    }


    ////////////////////////////////////////////////////////////////////////////////
    // event handlers for state STARTGAME
    ////////////////////////////////////////////////////////////////////////////////

    private void STARTGAME_enter()
    {
        this.stateId = StateId.STARTGAME;
    }

    private void STARTGAME_exit()
    {
        this.stateId = StateId.ROOT;
    }

    private void STARTGAME_fourplayergame()
    {
        // StartGame behavior
        // uml: FourPlayerGame TransitionTo(DealFourPlayer)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            STARTGAME_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `DealFourPlayer`.
            DEALFOURPLAYER_enter();

            // DealFourPlayer.<InitialState> behavior
            // uml: TransitionTo(Deal4_FirstPlayer)
            {
                // Step 1: Exit states until we reach `DealFourPlayer` state (Least Common Ancestor for transition). Already at LCA, no exiting required.

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `Deal4_FirstPlayer`.
                DEAL4_FIRSTPLAYER_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for DealFourPlayer.<InitialState>
        } // end of behavior for StartGame

        // No ancestor handles this event.
    }

    private void STARTGAME_twoplayergame()
    {
        // StartGame behavior
        // uml: TwoPlayerGame TransitionTo(DealTwoPlayer)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
            STARTGAME_exit();

            // Step 2: Transition action: ``.

            // Step 3: Enter/move towards transition target `DealTwoPlayer`.
            DEALTWOPLAYER_enter();

            // DealTwoPlayer.<InitialState> behavior
            // uml: TransitionTo(Deal2_FirstPlayer)
            {
                // Step 1: Exit states until we reach `DealTwoPlayer` state (Least Common Ancestor for transition). Already at LCA, no exiting required.

                // Step 2: Transition action: ``.

                // Step 3: Enter/move towards transition target `Deal2_FirstPlayer`.
                DEAL2_FIRSTPLAYER_enter();

                // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
                return;
            } // end of behavior for DealTwoPlayer.<InitialState>
        } // end of behavior for StartGame

        // No ancestor handles this event.
    }

    // Thread safe.
    public static string StateIdToString(StateId id)
    {
        switch (id)
        {
            case StateId.ROOT: return "ROOT";
            case StateId.ADD10POINTSTODEALER: return "ADD10POINTSTODEALER";
            case StateId.DEALFOURPLAYER: return "DEALFOURPLAYER";
            case StateId.DEAL4_FIRSTPLAYER: return "DEAL4_FIRSTPLAYER";
            case StateId.DEAL4_FOURTHPLAYER: return "DEAL4_FOURTHPLAYER";
            case StateId.DEAL4_SECONDPLAYER: return "DEAL4_SECONDPLAYER";
            case StateId.DEAL4_THIRDPLAYER: return "DEAL4_THIRDPLAYER";
            case StateId.DEALTWOPLAYER: return "DEALTWOPLAYER";
            case StateId.DEAL2_FIRSTPLAYER: return "DEAL2_FIRSTPLAYER";
            case StateId.DEAL2_SECONDPLAYER: return "DEAL2_SECONDPLAYER";
            case StateId.FLIPTRUMP: return "FLIPTRUMP";
            case StateId.PLAYPHASE1: return "PLAYPHASE1";
            case StateId.STARTGAME: return "STARTGAME";
            default: return "?";
        }
    }

    // Thread safe.
    public static string EventIdToString(EventId id)
    {
        switch (id)
        {
            case EventId.COMPLETE: return "COMPLETE";
            case EventId.DEALNOTCOMPLETE: return "DEALNOTCOMPLETE";
            case EventId.DO: return "DO";
            case EventId.FOURPLAYERGAME: return "FOURPLAYERGAME";
            case EventId.OTHERCARD: return "OTHERCARD";
            case EventId.TRUMP7: return "TRUMP7";
            case EventId.TWOPLAYERGAME: return "TWOPLAYERGAME";
            default: return "?";
        }
    }
}
